---
title: "Exploración plantas extintas"
author: "Jose Miranda"
date: "2022-08-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
```

## Introduccion 

### De donde vienen los datos 

   Estos datos de Plantas  extintas son datos de la **IUCN** , y se obtuvieron del [siguiente depositorio](rfordatascience/tidytuesday) de github


```{r,echo=FALSE , message= FALSE , warning=FALSE}
plants <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/plants.csv')
actions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/actions.csv')
threats <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/threats.csv')
```

##Datos de sudamerica

El numero de especies que hay en sudamerica en la base de datos es de `r plants %>% dplyr::filter(continent == "South America") %>% nrow()` especies 


